### ISSUE TITLE
cupy.dev down: Error 526 Invalid SSL certificate

### ISSUE THREAD

**Issue by aktech** [cupy/cupy.dev#27]
It seems the SSL certificate has expired for cupy.dev

<img width="1453" alt="Screenshot 2020-10-15 at 12 44 34" src="https://user-images.githubusercontent.com/5647941/96113236-2f126880-0ee4-11eb-9de7-204a4fbfa792.png">

**Comment by kmaehashi** [comment]
Thank you for reporting! I've fixed misconfiguration in Cloudflare. The issue should now be gone.

**Comment by aktech** [comment]
Thanks for fixing!
