### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by headtr1ck** [cupy/cupy.dev#60]
It would be nice to have an SVG version of the logo.

Does anyone know what font was used for the text?

**Comment by kmaehashi** [comment]
Thanks for the feedback! I'll try finding SVG, we should have it somewhere.

FYI, the highest resolution available as of now is:
https://github.com/cupy/cupy/blob/master/docs/image/cupy_logo_1000px.png

**Comment by kmaehashi** [comment]
Added in https://github.com/cupy/cupy/pull/8182
